variables:
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"

test:
  image: golang:1.25
  except:
    - tags
  script:
    - make tidy
    - make test

release:
  image: golang:1.25
  only:
    - tags
  script:
    - make dists
    - cd build && find . -type f -name 'fritz-mcp*' -exec sha256sum {} \; > ../SHA256SUMS
  artifacts:
    paths:
      - build/
      - SHA256SUMS
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG"
