variables:
  RUNNER_GENERATE_ARTIFACTS_METADATA: "true"

build:
  image: golang:1.25
  before_script:
    - apt-get update && apt-get install -y xz-utils zip jq
  script:
    - make all
    - make checksums
  artifacts:
    paths:
      - dist/
    reports:
      cyclonedx: dist/sbom.json
